### ISSUE TITLE
Crash with "TypeError: Cannot add property parent, object is not extensible"

### ISSUE THREAD

**Issue by UberMouse** [rlaffers/xstate-ninja#2]
Love the look of this, but I can't try it out in our production app because I'm getting this crash on one of our primary machines. Believe the error is coming from [here](https://github.com/rlaffers/xstate-ninja/blob/master/packages/xstate-ninja-core/src/XStateNinja.ts#L168-L172)

The child it's crashing on is a spawned callback. Let me know if you need any more info to repro.

**Comment by rlaffers** [comment]
More info is needed indeed. What does the error say? Can you make a minimal repro on Codesandbox?

**Comment by UberMouse** [comment]
Yep, looks the problem is with an interaction with @xstate/immer, worked fine with the normal assign from xstate but crashed when I switched to the assign from @xstate/immer

https://codesandbox.io/s/immutable-breeze-mim7nw?file=/src/App.js

**Comment by rlaffers** [comment]
Should be fixed by https://github.com/rlaffers/xstate-ninja/commit/739b07731ac2023db27fd841560136305378f373
New version of xstate-ninja will go out soon.
