### ISSUE TITLE
Enhancement: Expo dev tools plugin

### ISSUE THREAD

**Issue by elliotsayes** [rlaffers/xstate-ninja#26]
For using XState Ninja with React Native + Expo
Docs: https://docs.expo.dev/debugging/devtools-plugins/
Examples: https://github.com/expo/dev-plugins

**Comment by rlaffers** [comment]
@elliotsayes I do not use React Native and thus supporting this platform is beyond the scope of this project. That being said, you are welcome to implement the support. PRs are welcome.
