### ISSUE TITLE
Not picking up XState machine on reload

### ISSUE THREAD

**Issue by AriFordsham** [rlaffers/xstate-ninja#4]
Thanks for this great tool!

I'm developing a React app using `webpack-dev-server`. The first time I start the server, Ninja works as expected. However, if I reload the page, I get the 'No state machines were found on the current page' screen, and I need to restart the dev server to get Ninja working again.

Redux dev tools pick up the transitions regardless.

**Comment by rlaffers** [comment]
Thanks for the report. Can you make a repro in Codesandbox please?

**Comment by AriFordsham** [comment]
Not sure how I would get webpack-dev-server and xstate-ninja running in a Codesandbox.

**Comment by rlaffers** [comment]
Please update your web extension to v1.7.1.
