### ISSUE TITLE
The 'xstate-ninja' library may need to update its package.json or typings

### ISSUE THREAD

**Issue by deden** [rlaffers/xstate-ninja#5]
working on a typescript project with vscode and vite, I got this vscode error :

```
Could not find a declaration file for module 'xstate-ninja'. '/project/node_modules/xstate-ninja/dist/xstate-ninja.js' implicitly has an 'any' type.
  There are types at '/project/node_modules/xstate-ninja/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'xstate-ninja' library may need to update its package.json or typings.ts(7016)
```

what should I do to fixed this issue? or this library may need to update the package.json?

Here's I found similar issue on SO https://stackoverflow.com/a/76212193

**Comment by rlaffers** [comment]
Thanks for the report, I will make a PR momentarily.

**Comment by deden** [comment]
Hi @rlaffers , thanks for updating.
however, the issue still exists in package `@xstate-ninja/react`
```
Could not find a declaration file for module '@xstate-ninja/react'....
```

How to reproduce:

```
import { useMachine } from '@xstate-ninja/react'
```

**Comment by rlaffers** [comment]
@deden Version @xstate-ninja/react@1.1.3 is out, should be fixed now.
