### ISSUE TITLE
Updates on @xstate-ninja/vue

### ISSUE THREAD

**Issue by Zehir** [rlaffers/xstate-ninja#7]
Hello,

This extension seems really good for debuging xstate, is there any eta about the `@xstate-ninja/vue` package ?
I notice it on npm but he has no code

Thanks

**Comment by rlaffers** [comment]
Yeah, there is no implementation for Vue yet. That package serves as a placeholder. I do not currently use Vue and I'm prioritizing implementing support for xstate v5, so this will have to wait. Contributions are welcome of course.
