### ISSUE TITLE
Actor of type machine is not a state machine

### ISSUE THREAD

**Issue by Zehir** [rlaffers/xstate-ninja#9]
Hello,

I have a beavior that I don't understand, the extention tell that my machine is not a state machine but why ? But after changing it back it's now a state machine.

On initial loading :

![image](https://github.com/rlaffers/xstate-ninja/assets/845225/4e7a248d-5334-4cb9-a260-6067e9563737)

Then I select the invocation
It's not an machine so the message is ok
![image](https://github.com/rlaffers/xstate-ninja/assets/845225/65ca5597-9fb0-4bd2-815d-e8056b8a7cf9)

Then I select back the machine
Now the context and stuff is displayed
![image](https://github.com/rlaffers/xstate-ninja/assets/845225/58589395-35c7-4b58-a840-2622e5514b9e)

**Comment by rlaffers** [comment]
This seems like a bug. Can you provide a minimal example of a state machine for reproducing this?

**Comment by Zehir** [comment]
> This seems like a bug. Can you provide a minimal example of a state machine for reproducing this?

There it is :
https://stackblitz.com/edit/vitejs-vite-tawx2z?file=src%2Fcomponents%2FHelloWorld.vue

Make sure to copy the preview url and open it in a new tab.

If the xstate console was open after the page loading it's working but when you refresh the page the side panel say that the machine is not a machine.

**Comment by rlaffers** [comment]
@Zehir I can no longer reproduce this issue. Can you confirm it's been fixed?

**Comment by Zehir** [comment]
@rlaffers Me neither thanks!

I have updated to 1.3.10 and extension 1.7.1 and it's seems to work.

I will re-open this issue if needed
